### ISSUE TITLE
move per bot settings out of config.yaml into database

### ISSUE THREAD

**Issue by knivey** [knivey/lolbot#110]
there are still several per bot config items still in config.yaml

```yaml
bots:
  4:                                                                                                                                                                                                                                                                                    
    linktitles: true                                                                                                                                                                                                                                                                    
    codesand: true                                                                                                                                                                                                                                                                      
    codesandMinAccess: "+"                                                                                                                                                                                                                                                              
    codesand_maxlines: 40                                                                                                                                                                                                                                                               
    youtube: true                                                                                                                                                                                                                                                                       
    youtube_thumb: false                                                                                                                                                                                                                                                                
    youtube_thumbwidth: 65                                                                                                                                                                                                                                                              
    youtube_pump_host: "http://127.0.0.1:1345/"                                                                                                                                                                                                                                         
    youtube_pump_key: "redacted"                                                                                                                                                                                                                                                         
    url_max: 35                                                                                                                                                                                                                                                                         
    listen: "0.0.0.0:1338"                                                                                                                                                                                                                                                              
    pump_host: "http://127.0.0.1:1345/"                                                                                                                                                                                                                                                 
    pump_key: "redacted"
```

Work on a good way to store these in the database, some of these settings could be stored as per channel overrides also
